import type { SeerrArrKind } from './seerr.types';

export const SEERR_PERMISSIONS = {
  ADMIN: 2,
  MANAGE_SETTINGS: 4,
  MANAGE_USERS: 8,
  MANAGE_REQUESTS: 16,
  REQUEST: 32,
  VOTE: 64,
  AUTO_APPROVE: 128,
  AUTO_APPROVE_MOVIE: 256,
  AUTO_APPROVE_TV: 512,
  REQUEST_4K: 1024,
  REQUEST_4K_MOVIE: 2048,
  REQUEST_4K_TV: 4096,
  REQUEST_ADVANCED: 8192,
  REQUEST_VIEW: 16384,
  AUTO_APPROVE_4K: 32768,
  AUTO_APPROVE_4K_MOVIE: 65536,
  AUTO_APPROVE_4K_TV: 131072,
  REQUEST_MOVIE: 262144,
  REQUEST_TV: 524288,
} as const;

export const DEFAULT_REQUEST_PERMISSIONS =
  SEERR_PERMISSIONS.REQUEST | SEERR_PERMISSIONS.AUTO_APPROVE;

export const SEERR_APPLICATION_TITLE = 'Moody Blues';

export const MEDIA_SERVER_UNCONFIGURED = 4;

export const JELLYFIN_SERVER_TYPE = 2;

export const ARR_INSTANCE_NAMES: Readonly<Record<SeerrArrKind, string>> = {
  sonarr: 'Sonarr',
  radarr: 'Radarr',
};
